### ISSUE TITLE
web 側の service-worker の動作確認・修正

### ISSUE THREAD

**Issue by yukinkomob** [katahiromz/katahiromz.github.io#1]
### 依頼内容

![Screen Shot 2022-06-20 at 21 45 25](https://user-images.githubusercontent.com/3205581/174604610-979d1d35-e3d3-4deb-9ee3-57d69d2400ad.png)

**Comment by katahiromz** [comment]
了解。

**Comment by katahiromz** [comment]
MacにもGoogle Chromeブラウザをインストールできるはずです。ブラウザの「開発者ツール (developer tool)」を使用して、service-worker とネットワーク通信が正しく行なわれているか確認して下さい。

**Comment by yukinkomob** [comment]
### Precache されたファイルを確認

読み込み時の動画：
https://drive.google.com/file/d/1jpncnAsRrjcv1OrxdoNGhNKURNd4jlQP/view?usp=sharing

Precache されたファイル一覧：
![Screen Shot 2022-06-27 at 21 41 37](https://user-images.githubusercontent.com/3205581/175944153-912c3928-8a35-4a67-982b-2429c0bec26b.png)

**Comment by katahiromz** [comment]
`/saimin/` と `/saimin/index.html` が重複しているような気がしますね。
`/saimin/jquery-ui.min.js` が割とデカい。

**Comment by katahiromz** [comment]
私は`favicon.ico`を軽量化 ~~します~~ しました。

**Comment by yukinkomob** [comment]
> /saimin/ と /saimin/index.html が重複しているような気がしますね。

これはsw.jsの指定で、"./" と "./index.html" を指定しているためですね。
これらはパスが異なるものの同じものを指しているので、重複する形になっているのだと思われます。

<img width="314" alt="Screen Shot 2022-06-27 at 22 11 14" src="https://user-images.githubusercontent.com/3205581/175949590-6e0f67c3-c1cb-4977-892b-8b981c5b5f70.png">

**Comment by katahiromz** [comment]
`icon-192.png`は Open Graph Protocol に使われていますが、これはもしかするとキャッシュ不要かもしれません。

**Comment by katahiromz** [comment]
> "./" と "./index.html" を指定しているためですね。

"./"に統一しましょう。

**Comment by yukinkomob** [comment]
> "./"に統一しましょう。

承知しました。

> /saimin/jquery-ui.min.js が割とデカい。

jquery-ui の利用範囲を絞れるならば、下記の custom download ページにて、より軽量化したファイルを取得することが可能と思われます。用途はダイアログ位ですかね？

https://jqueryui.com/download/

**Comment by katahiromz** [comment]
> 用途はダイアログ位ですかね？

ええ。

**Comment by yukinkomob** [comment]
了解です。
ただ、サイズはどれも1MB未満であり、これ以上軽量化しても体感的なメリットはほとんどない気がします。
将来的に機能を拡張していく見込みがあるなら、あえてここで機能を絞り込まずに、全体をカバーする形で置いておくのもありだと思いますが。。

**Comment by katahiromz** [comment]
`jquery-ui.min.js`はそのまま行きましょう。

**Comment by yukinkomob** [comment]
承知しました。

**Comment by katahiromz** [comment]
`icon-192.png`はキャッシュから削れますね？

**Comment by katahiromz** [comment]
削りました。
