### ISSUE TITLE
Web側の多言語対応について調査

### ISSUE THREAD

**Issue by yukinkomob** [katahiromz/katahiromz.github.io#3]

**Comment by katahiromz** [comment]
了解。

**Comment by yukinkomob** [comment]
### 依頼経緯

![Screen Shot 2022-06-20 at 22 19 34](https://user-images.githubusercontent.com/3205581/174610707-0a2c433b-998b-49e3-b862-9e924b10e8e9.png)

**Comment by katahiromz** [comment]
基本方針。

- `index.html`内の翻訳すべき文字列はそのまま埋め込む。
- `main.js`内の翻訳すべき文字列は、ファイル先頭の文字列定数として定義する。それらの定数のプレフィックスは`TEXT_`とする。
- 言語依存のコードには `// {{language-specific}}` のようにコメントする。
