### ISSUE TITLE
ボタンにアイコンを付与

### ISSUE THREAD

**Issue by yukinkomob** [katahiromz/katahiromz.github.io#4]

**Comment by katahiromz** [comment]
了解。

**Comment by yukinkomob** [comment]
## 依頼の経緯
![Screen Shot 2022-06-20 at 22 28 47](https://user-images.githubusercontent.com/3205581/174612392-beb89274-22f4-4951-8091-bd93b4f05d32.png)
![Screen Shot 2022-06-20 at 22 28 53](https://user-images.githubusercontent.com/3205581/174612411-55788bcf-d045-410d-b56c-b5dbe900cbcf.png)
![Screen Shot 2022-06-20 at 22 28 59](https://user-images.githubusercontent.com/3205581/174612418-d8dd7962-3bf2-4646-bbf9-57f0500a487c.png)
![Screen Shot 2022-06-20 at 22 29 13](https://user-images.githubusercontent.com/3205581/174612433-0e1e674d-6a01-4427-a9dc-99db7cb6d99b.png)
![Screen Shot 2022-06-20 at 22 29 20](https://user-images.githubusercontent.com/3205581/174612443-690cf3e4-baa8-4b37-8d9a-821221b707f0.png)

**Comment by yukinkomob** [comment]
### アイコン画像
![gear](https://user-images.githubusercontent.com/3205581/174612570-60bbc8b4-06f2-4756-8daf-0357ab3599b3.png)
![gear](https://user-images.githubusercontent.com/3205581/174612576-0dbeb57a-28bf-411b-8abb-f263f512d03a.svg)
![question](https://user-images.githubusercontent.com/3205581/174612590-607ecbaa-f285-4e83-b317-8b0e8ce5f002.png)
![question](https://user-images.githubusercontent.com/3205581/174612593-6f3bddb3-fd03-4734-84fa-f950c1030746.svg)
[icons.zip](https://github.com/katahiromz/katahiromz.github.io/files/8940998/icons.zip)

**Comment by yukinkomob** [comment]
丸ボタンCSS
https://webukatu.com/wordpress/blog/5607/

**Comment by yukinkomob** [comment]
本ブランチの方で対応された

![Screen Shot 2022-06-22 at 12 34 46](https://user-images.githubusercontent.com/3205581/174938028-f8500c93-f191-4616-9d90-b8efd8b9b028.png)

**Comment by yukinkomob** [comment]
本タスクの作業は完了しているのでCloseとする
