### ISSUE TITLE
設定・ヘルプボタンの位置を移動

### ISSUE THREAD

**Issue by yukinkomob** [katahiromz/katahiromz.github.io#5]
設定ボタンは左上。ヘルプボタンは右上。

**Comment by katahiromz** [comment]
了解。

**Comment by yukinkomob** [comment]
本ブランチの方で対応済みのため、Closeする。

![Screen Shot 2022-06-22 at 12 34 46](https://user-images.githubusercontent.com/3205581/174938234-52359c89-7796-40fe-901c-3b928a07ea41.png)
